# Generated by Django 2.1.9 on 2019-06-14 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField(blank=True, null=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Version')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('chapter', models.IntegerField(default=1)),
                ('slug', helpers.fields.AutoSlugField(blank=True, max_length=255, set_once=True, set_using='heading')),
                ('verse', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book')),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentary.Commentary')),
            ],
            options={
                'ordering': ('commentary', 'book', 'chapter', 'verse'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('span', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
