# Generated by Django 2.1.2 on 2018-10-05 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import universal.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alt_name', models.CharField(blank=True, max_length=100)),
                ('position', models.IntegerField()),
                ('testament', models.CharField(max_length=20)),
                ('slug', universal.fields.AutoSlugField(blank=True, set_once=True, set_using='name')),
                ('deutero', models.BooleanField(default=False)),
                ('location', models.URLField(blank=True)),
                ('about', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['position', 'testament', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.IntegerField()),
                ('location', models.URLField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Book')),
            ],
            options={
                'ordering': ('book', 'number'),
            },
        ),
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('year', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('heading', models.CharField(blank=True, max_length=500)),
                ('chapter', models.IntegerField(default=1)),
                ('slug', universal.fields.AutoSlugField(blank=True, max_length=255, set_once=True, set_using='heading')),
                ('verse', models.IntegerField(default=1)),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Book')),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Commentary')),
            ],
            options={
                'ordering': ('commentary', 'book', 'chapter', 'verse'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField()),
                ('span', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=600)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Chapter')),
            ],
            options={
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', universal.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', universal.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', universal.fields.AutoSlugField(blank=True, set_once=True, set_using='name')),
                ('location', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commentary',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Version'),
        ),
        migrations.AddField(
            model_name='book',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drb.Version'),
        ),
    ]
