# Generated by Django 2.0.4 on 2018-04-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='slug',
        ),
    ]
