# Generated by Django 2.0.4 on 2018-04-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0002_remove_chapter_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verse',
            name='slug',
        ),
    ]
