# Generated by Django 2.0.4 on 2018-04-23 18:37

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0003_remove_verse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarytext',
            name='slug',
            field=universal.fields.AutoSlugField(blank=True, set_once=True, set_using='heading'),
        ),
    ]
