# Generated by Django 2.0.4 on 2018-04-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0004_auto_20180423_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentarytext',
            name='slug',
        ),
    ]
