# Generated by Django 2.0.4 on 2018-04-23 18:47

from django.db import migrations
import universal.fields


class Migration(migrations.Migration):

    dependencies = [
        ('drb', '0006_commentarytext_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarytext',
            name='slug',
            field=universal.fields.AutoSlugField(blank=True, max_length=255, set_once=True, set_using='heading'),
        ),
    ]
