# Generated by Django 2.1.9 on 2019-06-14 11:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import helpers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.IntegerField()),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['chapter', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ('document', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', helpers.fields.AutoSlugField(blank=True, set_once=True, set_using='name')),
                ('location', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('promulgation_date', models.DateField()),
                ('latin_name', models.CharField(max_length=50, unique=True)),
                ('english_name', models.CharField(blank=True, max_length=150)),
                ('position', models.IntegerField()),
                ('slug', helpers.fields.AutoSlugField(blank=True, set_once=True, set_using='latin_name')),
                ('location', models.URLField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.Category')),
                ('council', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.Council')),
                ('pontiff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Pope')),
            ],
            options={
                'ordering': ['council', 'latin_name'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('number', models.IntegerField()),
                ('text', models.CharField(max_length=1000)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.Article')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.Document'),
        ),
        migrations.AddField(
            model_name='article',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='council.Chapter'),
        ),
    ]
