# Generated by Django 2.1.2 on 2018-10-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date',
            new_name='promulgation_date',
        ),
    ]
