# Generated by Django 2.1.2 on 2018-10-13 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0003_document_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.Category'),
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.TextField(),
        ),
    ]
