# Generated by Django 2.1.2 on 2018-10-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('council', '0004_auto_20181013_2158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paragraph',
            new_name='Article',
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='council.Category'),
        ),
    ]
