# Generated by Django 2.2.2 on 2019-06-14 21:57

from django.db import migrations, models
import django.utils.timezone
import helpers.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', helpers.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', helpers.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('papal_name', models.CharField(max_length=50)),
                ('begin', models.DateField()),
                ('finish', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
