# Generated by Django 2.1.2 on 2018-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_auto_20181013_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontiff',
            name='first_name',
            field=models.CharField(default='nothin', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pontiff',
            name='last_name',
            field=models.CharField(default='nothing', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pontiff',
            name='papal_name',
            field=models.CharField(default='nothing', max_length=50),
            preserve_default=False,
        ),
    ]
