# Generated by Django 2.0.6 on 2018-07-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0003_auto_20180707_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
